name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Make Maven wrapper executable
        run: |
          cd backend
          chmod +x ./mvnw
      
      - name: Build with Maven
        run: |
          cd backend
          ./mvnw clean package -DskipTests
          
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "urbandrives"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true
      
      - name: Build and push Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web --app urbandrives
      
      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app urbandrives