name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Make Maven wrapper executable
        run: |
          cd backend
          chmod +x ./mvnw
      
      - name: Build with Maven
        run: |
          cd backend
          ./mvnw clean package -DskipTests
      
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          export PATH="/usr/local/bin:$PATH"
          export PATH="/usr/local/lib/heroku/bin:$PATH"
      
      - name: Login to Heroku Container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          which heroku || echo "Heroku not found"
          /usr/local/bin/heroku container:login
      
      - name: Build and push Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: /usr/local/bin/heroku container:push web --app urbandrives
      
      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: /usr/local/bin/heroku container:release web --app urbandrives